name: CI

on: [push, pull_request]

jobs:
  wasm:
    name: WASM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ProjectorRays
        uses: actions/checkout@v3
      - name: Set up Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 3.1.58
      - name: Build WASM
        run: |
          make wasm
      - name: Upload WASM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: projectorrays-wasm
          path: |
            projectorrays.js
            projectorrays.wasm
            projectorrays.d.ts
      - name: Release WASM artifacts
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            projectorrays.js
            projectorrays.wasm
            projectorrays.d.ts
